[package]
name = "ownership_bellshade"
version = "0.1.0"
edition = "2021"
authors = ["Rahman Hakim <rahmanhakim2435@protonmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
